gems: [jekyll-paginate]
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Confessions Of An Aspie
tagline:          'Life with Aspergers'
description:      'One person`s view on a confusing world.'
url:              http://confessionsofanaspie.net
baseurl:          /

author:
  name:           'Michael SanAngelo'
  url:            http://thelonegeek.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jms1989/confessionsofanaspie
